# Generated by Django 3.0.7 on 2020-06-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tea',
            name='form',
            field=models.CharField(choices=[('ball_rolled', 'Ball Rolled'), ('loose', 'Loose'), ('pressed', 'Pressed'), ('powdered', 'powdered')], default='loose', max_length=20),
        ),
        migrations.AddField(
            model_name='tea',
            name='origin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tea',
            name='picking_season',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tea',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tea',
            name='url_bought',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tea',
            name='vendor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='tea',
            name='vendor_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tea',
            name='would_buy_again',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
