# Generated by Django 3.1.6 on 2021-03-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teas', '0004_tea_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tea',
            name='category',
            field=models.CharField(choices=[('white', 'White'), ('green', 'Green'), ('yellow', 'Yellow'), ('oolong', 'Oolong'), ('black', 'Black'), ('fermented', 'Fermented')], default='oolong', max_length=20),
            preserve_default=False,
        ),
    ]
