# Generated by Django 3.2 on 2021-04-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teas', '0005_tea_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tea',
            name='status',
            field=models.CharField(choices=[('O', 'Ordered'), ('F', 'Finished'), ('A', 'Available')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='tea',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
